name       : extra-cmake-modules
version    : 5.28.0
release    : 3
source     :
    - http://download.kde.org/stable/frameworks/5.28/extra-cmake-modules-5.28.0.tar.xz : 50b40f7e755aa727d2b38a7d48885d4a457046676937b4f848a074041a06267a
license    : BSD-3-Clause
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WebKit)
setup      : |
    #We use qmake rather than qmake-qt5
    sed -i 's/qmake-qt5/qmake/' modules/ECMQueryQmake.cmake
    %patch -p1 < $pkgfiles/0001-Enable-stateless-paths.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
