name       : extra-cmake-modules
version    : 5.93.0
release    : 64
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.93/extra-cmake-modules-5.93.0.tar.xz : 093dea7b11647bc5f74e6971d47ef15b5c410cba2b4620acae00f008d5480b21
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Designer)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/ECM/html
