name       : extra-cmake-modules
version    : 5.47.0
release    : 19
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.47/extra-cmake-modules-5.47.0.tar.xz : 976d8bd15a0b929376bfaef34602a0fb9614229851c46fac3c4b28938f682195
license    : BSD-3-Clause
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WebKit)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    # We use qmake rather than qmake-qt5
    sed -i 's/qmake-qt5/qmake/' modules/ECMQueryQmake.cmake
    %patch -p1 < $pkgfiles/0001-Enable-stateless-paths.patch
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
