name       : extra-cmake-modules
version    : 5.52.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.52/extra-cmake-modules-5.52.0.tar.xz : 68c08aac2611e3faded476a5bba5ba56f8ed964374810bfcee93c6a7fa419b49
license    : BSD-3-Clause
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WebKit)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    # We use qmake rather than qmake-qt5
    sed -i 's/qmake-qt5/qmake/' modules/ECMQueryQmake.cmake
    %patch -p1 < $pkgfiles/0001-Enable-stateless-paths.patch
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
