name       : extra-cmake-modules
version    : 5.66.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.66/extra-cmake-modules-5.66.0.tar.xz : 2ff1a4ede28488ea787e742ab37edaacc5f59bf9188476e48f681ce23300b9c4
homepage   : https://community.kde.org/Frameworks
license    : BSD-3-Clause
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WebKit)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
