name       : extra-cmake-modules
version    : 5.92.0
release    : 63
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.92/extra-cmake-modules-5.92.0.tar.xz : f89a238bc5f28738db25e29296b75b4f795e3e9bfe3a8f1f9390648749d303ef
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Designer)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/ECM/html
