name       : extra-cmake-modules
version    : 5.82.0
release    : 54
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.82/extra-cmake-modules-5.82.0.tar.xz : 5972ec6d78c3e95ab9cbecdb0661c158570e868466357c5cec2b63a4251ecce4
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Designer)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/ECM/html
