name       : extra-cmake-modules
version    : 5.99.0
release    : 67
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.99/extra-cmake-modules-5.99.0.tar.xz : 01818aa606628db57129f6e22dbae3532464220802d085c6e0689d032e87807e
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Designer)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/ECM/html
