name       : extra-cmake-modules
version    : 5.40.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.40/extra-cmake-modules-5.40.0.tar.xz : 83e48889c84474e4f560e10e4eea0cc529f8511b3bd0415fcb898ac0496e630a
license    : BSD-3-Clause
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WebKit)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    #We use qmake rather than qmake-qt5
    sed -i 's/qmake-qt5/qmake/' modules/ECMQueryQmake.cmake
    %patch -p1 < $pkgfiles/0001-Enable-stateless-paths.patch
    %cmake -DBUILD_QTHELP_DOCS=ON .
build      : |
    %make
install    : |
    %make_install
    #Note these are for packaging purposes
    install -D -m 00755 $pkgfiles/qml_cache.sh $installdir/usr/bin/qml_cache
