name       : extra-cmake-modules
version    : 5.38.0
release    : 8
source     :
    - https://download.kde.org/stable/frameworks/5.38/extra-cmake-modules-5.38.0.tar.xz : 6188a8ac8d799439204f69a1eb229431fc9f196790b88d6fb72bb3d57edb2332
license    : BSD-3-Clause
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WebKit)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    #We use qmake rather than qmake-qt5
    sed -i 's/qmake-qt5/qmake/' modules/ECMQueryQmake.cmake
    %patch -p1 < $pkgfiles/0001-Enable-stateless-paths.patch
    %cmake -DBUILD_QTHELP_DOCS=ON .
build      : |
    %make
install    : |
    %make_install
    #Note these are for packaging purposes
    install -D -m 00755 $pkgfiles/qml_cache.sh $installdir/usr/bin/qml_cache
