name       : extra-cmake-modules
version    : 5.107.0
release    : 72
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.107/extra-cmake-modules-5.107.0.tar.xz : 3969aad56d1e6a5901e926aaf7a73510d98c4b363564ed3f1222d4135da633ed
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Designer)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/ECM/html
