name       : extra-cmake-modules
version    : 5.84.0
release    : 56
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.84/extra-cmake-modules-5.84.0.tar.xz : bb085ef2e177c182ff46988516b6b31849d1497beb2ff5301165ad2ba12a1c41
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Designer)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/ECM/html
