name       : extra-cmake-modules
version    : 5.106.0
release    : 71
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.106/extra-cmake-modules-5.106.0.tar.xz : 404f58ecac5d37485e51472ff5f88149f460689bec8792ea29bae279e63cb598
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Designer)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/ECM/html
