name       : extra-cmake-modules
version    : 5.83.0
release    : 55
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.83/extra-cmake-modules-5.83.0.tar.xz : 72b7f3b3917f3208fff10f0402b0fa3a65815aca924f0f94a4f96383d8e0f81e
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Designer)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/ECM/html
