name       : extra-cmake-modules
version    : 5.100.0
release    : 68
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.100/extra-cmake-modules-5.100.0.tar.xz : 34563ce7bbe3c4d8f69ce1f5dc87ae052443a6b0349fefb9e244a7358b16c0c5
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Designer)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/ECM/html
