name       : extra-cmake-modules
version    : 5.85.0
release    : 57
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.85/extra-cmake-modules-5.85.0.tar.xz : 7a4209c3b113dc50250920186a2d30b71870e11ebb92a700a611b423ce6b6634
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Designer)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/ECM/html
