name       : extra-cmake-modules
version    : 5.78.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.78/extra-cmake-modules-5.78.0.tar.xz : eede1f0c21f24eca56bd71a805fa76500a8c683bf21982cb33f4bba682d012f9
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WebKit)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/ECM/html
