name       : extra-cmake-modules
version    : 5.64.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.64/extra-cmake-modules-5.64.0.tar.xz : 1865efc6254bed44e0a6918c5af3da62be4008ba7a197a47f35251f298041a69
license    : BSD-3-Clause
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WebKit)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
