name       : extra-cmake-modules
version    : 5.67.0
release    : 39
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/extra-cmake-modules-5.67.0.tar.xz : e803f8740819a5620095c161883c26aaf1267d6f919d547fdd6414e7cccc0150
homepage   : https://community.kde.org/Frameworks
license    : BSD-3-Clause
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WebKit)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
