name       : extra-cmake-modules
version    : 5.91.0
release    : 62
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.91/extra-cmake-modules-5.91.0.tar.xz : 9717885e30aadf184fa71511930409cabbf08eb6627ea8b051de8804fbcec54c
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Designer)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/ECM/html
