name       : extra-cmake-modules
version    : 5.63.0
release    : 35
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.63/extra-cmake-modules-5.63.0.tar.xz : 79926a0a2c6f5aa760a5a63209a7cad641476591b9bf4e51819f4fb752280792
license    : BSD-3-Clause
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WebKit)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
