name       : extra-cmake-modules
version    : 5.81.0
release    : 53
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.81/extra-cmake-modules-5.81.0.tar.xz : 5f57e4b843069b6098d955051bb2913558d1623fead3f3b95b7017d7e1e35b83
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Designer)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/ECM/html
