name       : extra-cmake-modules
version    : 5.79.0
release    : 51
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.79/extra-cmake-modules-5.79.0.tar.xz : b29602db99c566d88fa92106abe114bd57b7ffc6ca20773426f896ffde68bed8
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Designer)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/ECM/html
