name       : extra-cmake-modules
version    : 5.65.0
release    : 37
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.65/extra-cmake-modules-5.65.0.tar.xz : 41634536ca1165a758acd85aa11112177616019e2d3974693a92d1d9bc91c105
license    : BSD-3-Clause
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WebKit)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
