name       : extra-cmake-modules
version    : 5.94.0
release    : 65
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.94/extra-cmake-modules-5.94.0.tar.xz : 23548a8ce2b998cfa675fc00112bf93914ee25194f0bfdf832d283c8d678d279
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Designer)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/ECM/html
