name       : extra-cmake-modules
version    : 5.88.0
release    : 59
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.88/extra-cmake-modules-5.88.0.tar.xz : 33bd83908daa531654455b77fc121b598f757aadf8ba01dbacfda8b8fb050319
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Designer)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/ECM/html
