name       : extra-cmake-modules
version    : 5.36.0
release    : 7
source     :
    - https://download.kde.org/stable/frameworks/5.36/extra-cmake-modules-5.36.0.tar.xz : 6e120bb40411ef559583ef693c0c03a41df3bb40a932bf7444c97e04266d5daf
license    : BSD-3-Clause
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WebKit)
    - python-sphinx
setup      : |
    #We use qmake rather than qmake-qt5
    sed -i 's/qmake-qt5/qmake/' modules/ECMQueryQmake.cmake
    %patch -p1 < $pkgfiles/0001-Enable-stateless-paths.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
    #Note these are for packaging purposes
    install -D -m 00755 $pkgfiles/qml_cache.sh $installdir/usr/bin/qml_cache
