name       : extra-cmake-modules
version    : 5.109.0
release    : 73
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.109/extra-cmake-modules-5.109.0.tar.xz : 1526b557cf9718e4d3bf31ff241578178d1ee60bdfb863110c97d43d478b7fb7
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Designer)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/ECM/html
