name       : extra-cmake-modules
version    : 5.71.0
release    : 43
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.71/extra-cmake-modules-5.71.0.tar.xz : 64f41c0b4b3164c7be8fcab5c0181253d97d1e9d62455fd540cb463afd051878
homepage   : https://community.kde.org/Frameworks
license    : BSD-3-Clause
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WebKit)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
