name       : extra-cmake-modules
version    : 5.25.0
release    : 1
source     :
    - http://download.kde.org/stable/frameworks/5.25/extra-cmake-modules-5.25.0.tar.xz : 73c90e67c328076c2bee35884836087e7e9f753e48fc0063c8348b6f66b0345f
license    : BSD-3-Clause
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebKit)
setup      : |
    #We use qmake rather than qmake-qt5
    sed -i 's/qmake-qt5/qmake/' modules/ECMQueryQmake.cmake
    %cmake .
build      : |
    %make
install    : |
    %make_install
