name       : extra-cmake-modules
version    : 5.90.0
release    : 61
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.90/extra-cmake-modules-5.90.0.tar.xz : f3007c3ceca56249292cf340a38518589a55a4afcf27e166ab63c5ac8ffabcb0
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Designer)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/ECM/html
