name       : extra-cmake-modules
version    : 5.80.0
release    : 52
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.80/extra-cmake-modules-5.80.0.tar.xz : 2370fd80f685533d0b96efa6fa443ceea68e0ceba4e8a9d7c151d297b1c96f64
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Designer)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/ECM/html
