name       : extra-cmake-modules
version    : 5.58.0
release    : 30
source     :
    - https://download.kde.org/stable/frameworks/5.58/extra-cmake-modules-5.58.0.tar.xz : 514011c12eeb2ac99d3118975832a279af2c2eea5e8b36b49c81962930b2ecc7
license    : BSD-3-Clause
component  : programming.devel
summary    : Extra cmake modules and scripts for KF5.
description: |
    Extra cmake modules and scripts for KF5.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WebKit)
    - doxygen
    - python-sphinx
rundeps    :
    - doxygen
setup      : |
    # We use qmake rather than qmake-qt5
    sed -i 's/qmake-qt5/qmake/' modules/ECMQueryQmake.cmake
    %patch -p1 < $pkgfiles/0001-Enable-stateless-paths.patch
    %cmake_ninja -DBUILD_QTHELP_DOCS=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
